version: "3.1"

services:
  db:
    image: postgres:12.6-alpine
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: remix-app-template
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 10
      start_period: 3s
    ports:
      - 5432:5432
    volumes:
      - ./.cache/db/data:/var/lib/postgresql/data
    restart: unless-stopped

  db-wait:
    image: busybox
    depends_on:
      db:
        condition: service_healthy
